# Generated by Django 3.1.14 on 2022-03-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220328_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sorting_int']},
        ),
    ]
